/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export interface DataPatchHara {
    hrId?: string;
    userId?: number | null;
    projectId?: number | null;
    hazardousEventId?: number | null;
    hazardId?: number | null;
    existingExternalMeasureId?: number | null;
    initialSeverityId?: number | null;
    initialSeverityJustification?: string | null;
    initialExposureId?: number | null;
    initialExposureJustification?: string | null;
    initialAvoidabilityId?: number | null;
    initialAvoidabilityJustification?: string | null;
    initialRiskClassId?: number | null;
    targetRiskReductionMeasureTypeId?: number | null;
    safetyTargetType?: string | null;
    allocatedSILId?: number | null;
    riskReductionMeasureId?: number | null;
    finalSeverityId?: number | null;
    finalSeverityJustification?: string | null;
    finalExposureId?: number | null;
    finalExposureJustification?: string | null;
    finalAvoidabilityId?: number | null;
    finalAvoidabilityJustification?: string | null;
    finalRiskClassId?: number | null;
    remarks?: string | null;
    shortDescription?: string | null;
    longDescription?: string | null;
    created?: string;
    creator?: string;
    metadata?: string | null;
    updated?: string | null;
    updaterIdentityUuid?: string | null;
    valid?: boolean;
    archived?: boolean;
    cacheKey?: string | null;
    integrityKey?: string | null;
    deidentified?: boolean;
    deidentifiedTimestamp?: number | null;
    markedForExpungepment?: boolean;
    expungementTimestamp?: number | null;
    containsSensitiveData?: boolean;
    sensitivityClassificationTypeEnum?: string;
    version?: string;
    correlationUuid?: string | null;
    externalId?: string | null;
    comment?: string | null;
    recordType?: string | null;
    allocatedSILUuid?: string | null;
    existingExternalMeasureUuid?: string | null;
    finalAvoidabilityUuid?: string | null;
    finalExposureUuid?: string | null;
    finalRiskClassUuid?: string | null;
    finalSeverityUuid?: string | null;
    hazardUuid?: string | null;
    hazardousEventUuid?: string | null;
    initialAvoidabilityUuid?: string | null;
    initialExposureUuid?: string | null;
    initialRiskClassUuid?: string | null;
    initialSeverityUuid?: string | null;
    projectUuid?: string | null;
    riskReductionMeasureUuid?: string | null;
    targetRiskReductionMeasureTypeUuid?: string | null;
    userUuid?: string | null;
}
