/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export interface DataPatchRiskEvaluation {
    type?: string;
    riskId?: number;
    stage?: "INITIAL" | "RESIDUAL";
    compositeSeverityOfInjury?: number | null;
    compositeFrequencyOfEvent?: number | null;
    compositePossibilityOfInjury?: number | null;
    severityOfInjuryMin?: number;
    severityOfInjuryMax?: number;
    severityOfInjuryVoteAllowed?: boolean | null;
    frequencyOfEventMin?: number;
    frequencyOfEventMax?: number;
    frequencyOfEventVoteAllowed?: boolean | null;
    possibilityOfInjuryMin?: number;
    possibilityOfInjuryMax?: number;
    possibilityOfInjuryVoteAllowed?: boolean | null;
    compositeRiskScore?: number | null;
    riskReductionMeasureComment?: string | null;
    shortDescription?: string | null;
    longDescription?: string | null;
    created?: string;
    creator?: string;
    metadata?: string | null;
    updated?: string | null;
    updaterIdentityUuid?: string | null;
    valid?: boolean;
    archived?: boolean;
    cacheKey?: string | null;
    integrityKey?: string | null;
    deidentified?: boolean;
    deidentifiedTimestamp?: number | null;
    markedForExpungepment?: boolean;
    expungementTimestamp?: number | null;
    containsSensitiveData?: boolean;
    sensitivityClassificationTypeEnum?: string;
    version?: string;
    correlationUuid?: string | null;
    externalId?: string | null;
    comment?: string | null;
    recordType?: string | null;
    riskUuid?: string;
}
