import type { FieldsCertificateAuthority } from "./FieldsCertificateAuthority";
import type { WhereCertificateAuthority } from "./WhereCertificateAuthority";
import type { OrderByCertificateAuthority } from "./OrderByCertificateAuthority";
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export declare type FieldsPki = (("id" | "name" | "description" | "siteUrl" | "logoUrl" | "policyName" | "policyUrl" | "isEnabled" | "uuid" | "shortDescription" | "longDescription" | "created" | "creator" | "metadata" | "updated" | "updaterIdentityUuid" | "valid" | "archived" | "cacheKey" | "integrityKey" | "deidentified" | "deidentifiedTimestamp" | "markedForExpungepment" | "expungementTimestamp" | "containsSensitiveData" | "sensitivityClassificationTypeEnum" | "version" | "correlationUuid" | "externalId" | "comment" | "recordType") | {
    name: "certificateAuthorityList";
    as?: string;
    fields: FieldsCertificateAuthority;
    args?: {
        $where?: WhereCertificateAuthority;
        $orderBy?: OrderByCertificateAuthority;
    };
})[];
