import type { FieldsRiskCategory } from "./FieldsRiskCategory";
import type { FieldsRiskCategoryAttribute } from "./FieldsRiskCategoryAttribute";
import type { WhereRiskCategoryAttributeType } from "./WhereRiskCategoryAttributeType";
import type { WhereRiskCategory } from "./WhereRiskCategory";
import type { WhereRiskCategoryAttribute } from "./WhereRiskCategoryAttribute";
import type { OrderByRiskCategoryAttribute } from "./OrderByRiskCategoryAttribute";
import type { OrderByRiskCategoryAttributeType } from "./OrderByRiskCategoryAttributeType";
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export declare type FieldsRiskCategoryAttributeType = (("id" | "riskCategoryId" | "parentId" | "enum" | "name" | "labelNumber" | "defaultValue" | "isRequired" | "jsonSchema" | "label" | "placeholderText" | "helpMarkdownText" | "isMedia" | "uuid" | "shortDescription" | "longDescription" | "created" | "creator" | "metadata" | "updated" | "updaterIdentityUuid" | "valid" | "archived" | "cacheKey" | "integrityKey" | "deidentified" | "deidentifiedTimestamp" | "markedForExpungepment" | "expungementTimestamp" | "containsSensitiveData" | "sensitivityClassificationTypeEnum" | "version" | "correlationUuid" | "externalId" | "comment" | "recordType" | "parentUuid" | "riskCategoryUuid") | {
    name: "riskCategoryAttributeType";
    as?: string;
    fields: FieldsRiskCategoryAttributeType;
    args?: {
        $where?: WhereRiskCategoryAttributeType;
    };
} | {
    name: "riskCategory";
    as?: string;
    fields: FieldsRiskCategory;
    args?: {
        $where?: WhereRiskCategory;
    };
} | {
    name: "riskCategoryAttributeList";
    as?: string;
    fields: FieldsRiskCategoryAttribute;
    args?: {
        $where?: WhereRiskCategoryAttribute;
        $orderBy?: OrderByRiskCategoryAttribute;
    };
} | {
    name: "riskCategoryAttributeTypeList";
    as?: string;
    fields: FieldsRiskCategoryAttributeType;
    args?: {
        $where?: WhereRiskCategoryAttributeType;
        $orderBy?: OrderByRiskCategoryAttributeType;
    };
})[];
