import type { FieldsRole } from "./FieldsRole";
import type { FieldsUser } from "./FieldsUser";
import type { WhereRole } from "./WhereRole";
import type { WhereUser } from "./WhereUser";
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export declare type FieldsUserRole = (("id" | "roleId" | "userId" | "uuid" | "shortDescription" | "longDescription" | "created" | "creator" | "metadata" | "updated" | "updaterIdentityUuid" | "valid" | "archived" | "cacheKey" | "integrityKey" | "deidentified" | "deidentifiedTimestamp" | "markedForExpungepment" | "expungementTimestamp" | "containsSensitiveData" | "sensitivityClassificationTypeEnum" | "version" | "correlationUuid" | "externalId" | "comment" | "recordType" | "roleUuid" | "userUuid") | {
    name: "role";
    as?: string;
    fields: FieldsRole;
    args?: {
        $where?: WhereRole;
    };
} | {
    name: "user";
    as?: string;
    fields: FieldsUser;
    args?: {
        $where?: WhereUser;
    };
})[];
