import type { FieldsProject } from "./FieldsProject";
import type { FieldsRiskCategory } from "./FieldsRiskCategory";
import type { WhereProject } from "./WhereProject";
import type { WhereRiskCategory } from "./WhereRiskCategory";
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export declare type FieldsRiskCategoryProject = (("id" | "riskCategoryId" | "projectId" | "uuid" | "shortDescription" | "longDescription" | "created" | "creator" | "metadata" | "updated" | "updaterIdentityUuid" | "valid" | "archived" | "cacheKey" | "integrityKey" | "deidentified" | "deidentifiedTimestamp" | "markedForExpungepment" | "expungementTimestamp" | "containsSensitiveData" | "sensitivityClassificationTypeEnum" | "version" | "correlationUuid" | "externalId" | "comment" | "recordType" | "projectUuid" | "riskCategoryUuid") | {
    name: "project";
    as?: string;
    fields: FieldsProject;
    args?: {
        $where?: WhereProject;
    };
} | {
    name: "riskCategory";
    as?: string;
    fields: FieldsRiskCategory;
    args?: {
        $where?: WhereRiskCategory;
    };
})[];
