import type { FieldsCspCapabilityCryptocmd } from "./FieldsCspCapabilityCryptocmd";
import type { WhereCspCapabilityCryptocmd } from "./WhereCspCapabilityCryptocmd";
import type { OrderByCspCapabilityCryptocmd } from "./OrderByCspCapabilityCryptocmd";
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export declare type FieldsCspCapabilityCryptocmdAlgorcmd = (("id" | "rsa" | "ecdsa" | "composite" | "uuid" | "shortDescription" | "longDescription" | "created" | "creator" | "metadata" | "updated" | "updaterIdentityUuid" | "valid" | "archived" | "cacheKey" | "integrityKey" | "deidentified" | "deidentifiedTimestamp" | "markedForExpungepment" | "expungementTimestamp" | "containsSensitiveData" | "sensitivityClassificationTypeEnum" | "version" | "correlationUuid" | "externalId" | "comment" | "recordType") | {
    name: "cspCapabilityCryptocmdList";
    as?: string;
    fields: FieldsCspCapabilityCryptocmd;
    args?: {
        $where?: WhereCspCapabilityCryptocmd;
        $orderBy?: OrderByCspCapabilityCryptocmd;
    };
})[];
