import type { FieldsCsp } from "./FieldsCsp";
import type { WhereCsp } from "./WhereCsp";
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export declare type FieldsCspCapability = (("id" | "cspId" | "keyDeleteCmdId" | "keyCreateCmdId" | "keyImportCmdId" | "keyExportCmdId" | "enabled" | "uuid" | "shortDescription" | "longDescription" | "created" | "creator" | "metadata" | "updated" | "updaterIdentityUuid" | "valid" | "archived" | "cacheKey" | "integrityKey" | "deidentified" | "deidentifiedTimestamp" | "markedForExpungepment" | "expungementTimestamp" | "containsSensitiveData" | "sensitivityClassificationTypeEnum" | "version" | "correlationUuid" | "externalId" | "comment" | "recordType" | "cspUuid") | {
    name: "csp";
    as?: string;
    fields: FieldsCsp;
    args?: {
        $where?: WhereCsp;
    };
})[];
