import type { FieldsRiskCategoryAttributeType } from "./FieldsRiskCategoryAttributeType";
import type { FieldsRiskCategory } from "./FieldsRiskCategory";
import type { WhereRiskCategoryAttributeType } from "./WhereRiskCategoryAttributeType";
import type { WhereRiskCategory } from "./WhereRiskCategory";
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export declare type FieldsRiskCategoryAttribute = (("id" | "riskCategoryId" | "riskCategoryAttributeTypeId" | "name" | "value" | "uuid" | "shortDescription" | "longDescription" | "created" | "creator" | "metadata" | "updated" | "updaterIdentityUuid" | "valid" | "archived" | "cacheKey" | "integrityKey" | "deidentified" | "deidentifiedTimestamp" | "markedForExpungepment" | "expungementTimestamp" | "containsSensitiveData" | "sensitivityClassificationTypeEnum" | "version" | "correlationUuid" | "externalId" | "comment" | "recordType" | "riskCategoryAttributeTypeUuid" | "riskCategoryUuid") | {
    name: "riskCategoryAttributeType";
    as?: string;
    fields: FieldsRiskCategoryAttributeType;
    args?: {
        $where?: WhereRiskCategoryAttributeType;
    };
} | {
    name: "riskCategory";
    as?: string;
    fields: FieldsRiskCategory;
    args?: {
        $where?: WhereRiskCategory;
    };
})[];
