import type { FieldsMedia } from "./FieldsMedia";
import type { FieldsRisk } from "./FieldsRisk";
import type { WhereMedia } from "./WhereMedia";
import type { WhereRisk } from "./WhereRisk";
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export declare type FieldsRiskMedia = (("id" | "riskId" | "mediaId" | "uuid" | "shortDescription" | "longDescription" | "created" | "creator" | "metadata" | "updated" | "updaterIdentityUuid" | "valid" | "archived" | "cacheKey" | "integrityKey" | "deidentified" | "deidentifiedTimestamp" | "markedForExpungepment" | "expungementTimestamp" | "containsSensitiveData" | "sensitivityClassificationTypeEnum" | "version" | "correlationUuid" | "externalId" | "comment" | "recordType" | "mediaUuid" | "riskUuid") | {
    name: "media";
    as?: string;
    fields: FieldsMedia;
    args?: {
        $where?: WhereMedia;
    };
} | {
    name: "risk";
    as?: string;
    fields: FieldsRisk;
    args?: {
        $where?: WhereRisk;
    };
})[];
