import type { FieldsConsideredSituationalAttribute } from "./FieldsConsideredSituationalAttribute";
import type { FieldsProject } from "./FieldsProject";
import type { FieldsHazardousEvent } from "./FieldsHazardousEvent";
import type { WhereConsideredSituationalAttribute } from "./WhereConsideredSituationalAttribute";
import type { WhereProject } from "./WhereProject";
import type { WhereHazardousEvent } from "./WhereHazardousEvent";
import type { OrderByHazardousEvent } from "./OrderByHazardousEvent";
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export declare type FieldsOdd = (("id" | "hrId" | "projectId" | "csaModeId" | "csaMotionId" | "csaLoadId" | "csaObstacleExposureId" | "description" | "remarks" | "uuid" | "shortDescription" | "longDescription" | "created" | "creator" | "metadata" | "updated" | "updaterIdentityUuid" | "valid" | "archived" | "cacheKey" | "integrityKey" | "deidentified" | "deidentifiedTimestamp" | "markedForExpungepment" | "expungementTimestamp" | "containsSensitiveData" | "sensitivityClassificationTypeEnum" | "version" | "correlationUuid" | "externalId" | "comment" | "recordType" | "csaLoadUuid" | "csaModeUuid" | "csaMotionUuid" | "csaObstacleExposureUuid" | "projectUuid") | {
    name: "consideredSituationalAttribute1";
    as?: string;
    fields: FieldsConsideredSituationalAttribute;
    args?: {
        $where?: WhereConsideredSituationalAttribute;
    };
} | {
    name: "consideredSituationalAttribute2";
    as?: string;
    fields: FieldsConsideredSituationalAttribute;
    args?: {
        $where?: WhereConsideredSituationalAttribute;
    };
} | {
    name: "consideredSituationalAttribute3";
    as?: string;
    fields: FieldsConsideredSituationalAttribute;
    args?: {
        $where?: WhereConsideredSituationalAttribute;
    };
} | {
    name: "consideredSituationalAttribute4";
    as?: string;
    fields: FieldsConsideredSituationalAttribute;
    args?: {
        $where?: WhereConsideredSituationalAttribute;
    };
} | {
    name: "project";
    as?: string;
    fields: FieldsProject;
    args?: {
        $where?: WhereProject;
    };
} | {
    name: "hazardousEventList";
    as?: string;
    fields: FieldsHazardousEvent;
    args?: {
        $where?: WhereHazardousEvent;
        $orderBy?: OrderByHazardousEvent;
    };
})[];
