import type { FieldsCertificateAuthority } from "./FieldsCertificateAuthority";
import type { FieldsCertificateAuthorityCertificateToken } from "./FieldsCertificateAuthorityCertificateToken";
import type { FieldsOrganizationCertificateToken } from "./FieldsOrganizationCertificateToken";
import type { FieldsOrganization } from "./FieldsOrganization";
import type { WhereCertificateAuthority } from "./WhereCertificateAuthority";
import type { WhereCertificateAuthorityCertificateToken } from "./WhereCertificateAuthorityCertificateToken";
import type { WhereOrganizationCertificateToken } from "./WhereOrganizationCertificateToken";
import type { WhereOrganization } from "./WhereOrganization";
import type { OrderByCertificateAuthorityCertificateToken } from "./OrderByCertificateAuthorityCertificateToken";
import type { OrderByOrganizationCertificateToken } from "./OrderByOrganizationCertificateToken";
import type { OrderByCertificateAuthority } from "./OrderByCertificateAuthority";
import type { OrderByOrganization } from "./OrderByOrganization";
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export declare type FieldsCertificateToken = (("id" | "issuerCertificateAuthorityId" | "standard" | "key" | "cert" | "isSelfSigned" | "caOwned" | "expires" | "revoked" | "uuid" | "shortDescription" | "longDescription" | "created" | "creator" | "metadata" | "updated" | "updaterIdentityUuid" | "valid" | "archived" | "cacheKey" | "integrityKey" | "deidentified" | "deidentifiedTimestamp" | "markedForExpungepment" | "expungementTimestamp" | "containsSensitiveData" | "sensitivityClassificationTypeEnum" | "version" | "correlationUuid" | "externalId" | "comment" | "recordType" | "issuerCertificateAuthorityUuid") | {
    name: "certificateAuthority";
    as?: string;
    fields: FieldsCertificateAuthority;
    args?: {
        $where?: WhereCertificateAuthority;
    };
} | {
    name: "certificateAuthorityCertificateTokenList";
    as?: string;
    fields: FieldsCertificateAuthorityCertificateToken;
    args?: {
        $where?: WhereCertificateAuthorityCertificateToken;
        $orderBy?: OrderByCertificateAuthorityCertificateToken;
    };
} | {
    name: "organizationCertificateTokenList";
    as?: string;
    fields: FieldsOrganizationCertificateToken;
    args?: {
        $where?: WhereOrganizationCertificateToken;
        $orderBy?: OrderByOrganizationCertificateToken;
    };
} | {
    name: "certificateAuthorityList";
    as?: string;
    fields: FieldsCertificateAuthority;
    args?: {
        $where?: WhereCertificateAuthority | [WhereCertificateAuthority, WhereCertificateAuthorityCertificateToken];
        $orderBy?: OrderByCertificateAuthority;
    };
} | {
    name: "organizationList";
    as?: string;
    fields: FieldsOrganization;
    args?: {
        $where?: WhereOrganization | [WhereOrganization, WhereOrganizationCertificateToken];
        $orderBy?: OrderByOrganization;
    };
})[];
