import type { FieldsFunctionTask } from "./FieldsFunctionTask";
import type { FieldsGuideword } from "./FieldsGuideword";
import type { FieldsProject } from "./FieldsProject";
import type { FieldsHazardousEvent } from "./FieldsHazardousEvent";
import type { WhereFunctionTask } from "./WhereFunctionTask";
import type { WhereGuideword } from "./WhereGuideword";
import type { WhereProject } from "./WhereProject";
import type { WhereHazardousEvent } from "./WhereHazardousEvent";
import type { OrderByHazardousEvent } from "./OrderByHazardousEvent";
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export declare type FieldsHazop = (("id" | "hrId" | "projectId" | "functionTaskId" | "guidewordId" | "resultingMalfunction" | "remarks" | "uuid" | "shortDescription" | "longDescription" | "created" | "creator" | "metadata" | "updated" | "updaterIdentityUuid" | "valid" | "archived" | "cacheKey" | "integrityKey" | "deidentified" | "deidentifiedTimestamp" | "markedForExpungepment" | "expungementTimestamp" | "containsSensitiveData" | "sensitivityClassificationTypeEnum" | "version" | "correlationUuid" | "externalId" | "comment" | "recordType" | "functionTaskUuid" | "guidewordUuid" | "projectUuid") | {
    name: "functionTask";
    as?: string;
    fields: FieldsFunctionTask;
    args?: {
        $where?: WhereFunctionTask;
    };
} | {
    name: "guideword";
    as?: string;
    fields: FieldsGuideword;
    args?: {
        $where?: WhereGuideword;
    };
} | {
    name: "project";
    as?: string;
    fields: FieldsProject;
    args?: {
        $where?: WhereProject;
    };
} | {
    name: "hazardousEventList";
    as?: string;
    fields: FieldsHazardousEvent;
    args?: {
        $where?: WhereHazardousEvent;
        $orderBy?: OrderByHazardousEvent;
    };
})[];
