import type { FieldsRiskDiscussionMessage } from "./FieldsRiskDiscussionMessage";
import type { FieldsRiskMedia } from "./FieldsRiskMedia";
import type { FieldsRisk } from "./FieldsRisk";
import type { WhereRiskDiscussionMessage } from "./WhereRiskDiscussionMessage";
import type { WhereRiskMedia } from "./WhereRiskMedia";
import type { WhereRisk } from "./WhereRisk";
import type { OrderByRiskDiscussionMessage } from "./OrderByRiskDiscussionMessage";
import type { OrderByRiskMedia } from "./OrderByRiskMedia";
import type { OrderByRisk } from "./OrderByRisk";
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export declare type FieldsMedia = (("id" | "name" | "type" | "mimeType" | "sourceMediaUrl" | "compressedMediaUrl" | "caption" | "sourceMediaKey" | "compressedMediaKey" | "storageLocation" | "originalFilename" | "isPublic" | "uuid" | "shortDescription" | "longDescription" | "created" | "creator" | "metadata" | "updated" | "updaterIdentityUuid" | "valid" | "archived" | "cacheKey" | "integrityKey" | "deidentified" | "deidentifiedTimestamp" | "markedForExpungepment" | "expungementTimestamp" | "containsSensitiveData" | "sensitivityClassificationTypeEnum" | "version" | "correlationUuid" | "externalId" | "comment" | "recordType") | {
    name: "riskDiscussionMessageList";
    as?: string;
    fields: FieldsRiskDiscussionMessage;
    args?: {
        $where?: WhereRiskDiscussionMessage;
        $orderBy?: OrderByRiskDiscussionMessage;
    };
} | {
    name: "riskMediaList";
    as?: string;
    fields: FieldsRiskMedia;
    args?: {
        $where?: WhereRiskMedia;
        $orderBy?: OrderByRiskMedia;
    };
} | {
    name: "riskList";
    as?: string;
    fields: FieldsRisk;
    args?: {
        $where?: WhereRisk | [WhereRisk, WhereRiskMedia];
        $orderBy?: OrderByRisk;
    };
})[];
