import type { FieldsAddress } from "./FieldsAddress";
import type { FieldsOrganization } from "./FieldsOrganization";
import type { WhereAddress } from "./WhereAddress";
import type { WhereOrganization } from "./WhereOrganization";
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export declare type FieldsOrganizationAddress = (("id" | "addressId" | "organizationId" | "isPrimary" | "uuid" | "shortDescription" | "longDescription" | "created" | "creator" | "metadata" | "updated" | "updaterIdentityUuid" | "valid" | "archived" | "cacheKey" | "integrityKey" | "deidentified" | "deidentifiedTimestamp" | "markedForExpungepment" | "expungementTimestamp" | "containsSensitiveData" | "sensitivityClassificationTypeEnum" | "version" | "correlationUuid" | "externalId" | "comment" | "recordType" | "addressUuid" | "organizationUuid") | {
    name: "address";
    as?: string;
    fields: FieldsAddress;
    args?: {
        $where?: WhereAddress;
    };
} | {
    name: "organization";
    as?: string;
    fields: FieldsOrganization;
    args?: {
        $where?: WhereOrganization;
    };
})[];
