import type { FieldsCertificateAuthority } from "./FieldsCertificateAuthority";
import type { FieldsOrganization } from "./FieldsOrganization";
import type { WhereCertificateAuthority } from "./WhereCertificateAuthority";
import type { WhereOrganization } from "./WhereOrganization";
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export declare type FieldsCertificateAuthorityOrganization = (("id" | "certificateAuthorityId" | "organizationId" | "status" | "uuid" | "shortDescription" | "longDescription" | "created" | "creator" | "metadata" | "updated" | "updaterIdentityUuid" | "valid" | "archived" | "cacheKey" | "integrityKey" | "deidentified" | "deidentifiedTimestamp" | "markedForExpungepment" | "expungementTimestamp" | "containsSensitiveData" | "sensitivityClassificationTypeEnum" | "version" | "correlationUuid" | "externalId" | "comment" | "recordType" | "certificateAuthorityUuid" | "organizationUuid") | {
    name: "certificateAuthority";
    as?: string;
    fields: FieldsCertificateAuthority;
    args?: {
        $where?: WhereCertificateAuthority;
    };
} | {
    name: "organization";
    as?: string;
    fields: FieldsOrganization;
    args?: {
        $where?: WhereOrganization;
    };
})[];
