import type { FieldsAsil } from "./FieldsAsil";
import type { FieldsGuideword } from "./FieldsGuideword";
import type { FieldsHazardType } from "./FieldsHazardType";
import type { FieldsPl } from "./FieldsPl";
import type { FieldsRiskAvoidability } from "./FieldsRiskAvoidability";
import type { FieldsRiskClass } from "./FieldsRiskClass";
import type { FieldsRiskExposure } from "./FieldsRiskExposure";
import type { FieldsRiskSeverity } from "./FieldsRiskSeverity";
import type { FieldsSil } from "./FieldsSil";
import type { WhereAsil } from "./WhereAsil";
import type { WhereGuideword } from "./WhereGuideword";
import type { WhereHazardType } from "./WhereHazardType";
import type { WherePl } from "./WherePl";
import type { WhereRiskAvoidability } from "./WhereRiskAvoidability";
import type { WhereRiskClass } from "./WhereRiskClass";
import type { WhereRiskExposure } from "./WhereRiskExposure";
import type { WhereRiskSeverity } from "./WhereRiskSeverity";
import type { WhereSil } from "./WhereSil";
import type { OrderByAsil } from "./OrderByAsil";
import type { OrderByGuideword } from "./OrderByGuideword";
import type { OrderByHazardType } from "./OrderByHazardType";
import type { OrderByPl } from "./OrderByPl";
import type { OrderByRiskAvoidability } from "./OrderByRiskAvoidability";
import type { OrderByRiskClass } from "./OrderByRiskClass";
import type { OrderByRiskExposure } from "./OrderByRiskExposure";
import type { OrderByRiskSeverity } from "./OrderByRiskSeverity";
import type { OrderBySil } from "./OrderBySil";
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export declare type FieldsStandard = (("id" | "hrId" | "standard" | "title" | "strict" | "url" | "uuid" | "shortDescription" | "longDescription" | "created" | "creator" | "metadata" | "updated" | "updaterIdentityUuid" | "valid" | "archived" | "cacheKey" | "integrityKey" | "deidentified" | "deidentifiedTimestamp" | "markedForExpungepment" | "expungementTimestamp" | "containsSensitiveData" | "sensitivityClassificationTypeEnum" | "version" | "correlationUuid" | "externalId" | "comment" | "recordType") | {
    name: "asilList";
    as?: string;
    fields: FieldsAsil;
    args?: {
        $where?: WhereAsil;
        $orderBy?: OrderByAsil;
    };
} | {
    name: "guidewordList";
    as?: string;
    fields: FieldsGuideword;
    args?: {
        $where?: WhereGuideword;
        $orderBy?: OrderByGuideword;
    };
} | {
    name: "hazardTypeList";
    as?: string;
    fields: FieldsHazardType;
    args?: {
        $where?: WhereHazardType;
        $orderBy?: OrderByHazardType;
    };
} | {
    name: "plList";
    as?: string;
    fields: FieldsPl;
    args?: {
        $where?: WherePl;
        $orderBy?: OrderByPl;
    };
} | {
    name: "riskAvoidabilityList";
    as?: string;
    fields: FieldsRiskAvoidability;
    args?: {
        $where?: WhereRiskAvoidability;
        $orderBy?: OrderByRiskAvoidability;
    };
} | {
    name: "riskClassList";
    as?: string;
    fields: FieldsRiskClass;
    args?: {
        $where?: WhereRiskClass;
        $orderBy?: OrderByRiskClass;
    };
} | {
    name: "riskExposureList";
    as?: string;
    fields: FieldsRiskExposure;
    args?: {
        $where?: WhereRiskExposure;
        $orderBy?: OrderByRiskExposure;
    };
} | {
    name: "riskSeverityList";
    as?: string;
    fields: FieldsRiskSeverity;
    args?: {
        $where?: WhereRiskSeverity;
        $orderBy?: OrderByRiskSeverity;
    };
} | {
    name: "silList";
    as?: string;
    fields: FieldsSil;
    args?: {
        $where?: WhereSil;
        $orderBy?: OrderBySil;
    };
})[];
