import type { FieldsProjectAttributeType } from "./FieldsProjectAttributeType";
import type { FieldsProject } from "./FieldsProject";
import type { FieldsProjectAttribute } from "./FieldsProjectAttribute";
import type { WhereProjectAttributeType } from "./WhereProjectAttributeType";
import type { WhereProject } from "./WhereProject";
import type { WhereProjectAttribute } from "./WhereProjectAttribute";
import type { OrderByProjectAttribute } from "./OrderByProjectAttribute";
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export declare type FieldsProjectAttributeTypeValue = (("id" | "projectId" | "projectAttributeTypeId" | "enum" | "name" | "value" | "uuid" | "shortDescription" | "longDescription" | "created" | "creator" | "metadata" | "updated" | "updaterIdentityUuid" | "valid" | "archived" | "cacheKey" | "integrityKey" | "deidentified" | "deidentifiedTimestamp" | "markedForExpungepment" | "expungementTimestamp" | "containsSensitiveData" | "sensitivityClassificationTypeEnum" | "version" | "correlationUuid" | "externalId" | "comment" | "recordType" | "projectAttributeTypeUuid" | "projectUuid") | {
    name: "projectAttributeType";
    as?: string;
    fields: FieldsProjectAttributeType;
    args?: {
        $where?: WhereProjectAttributeType;
    };
} | {
    name: "project";
    as?: string;
    fields: FieldsProject;
    args?: {
        $where?: WhereProject;
    };
} | {
    name: "projectAttributeList";
    as?: string;
    fields: FieldsProjectAttribute;
    args?: {
        $where?: WhereProjectAttribute;
        $orderBy?: OrderByProjectAttribute;
    };
})[];
