import type { FieldsProject } from "./FieldsProject";
import type { FieldsHara } from "./FieldsHara";
import type { FieldsRiskReductionMeasure } from "./FieldsRiskReductionMeasure";
import type { WhereProject } from "./WhereProject";
import type { WhereHara } from "./WhereHara";
import type { WhereRiskReductionMeasure } from "./WhereRiskReductionMeasure";
import type { OrderByHara } from "./OrderByHara";
import type { OrderByRiskReductionMeasure } from "./OrderByRiskReductionMeasure";
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export declare type FieldsRiskReductionMeasureType = (("id" | "projectId" | "name" | "description" | "uuid" | "shortDescription" | "longDescription" | "created" | "creator" | "metadata" | "updated" | "updaterIdentityUuid" | "valid" | "archived" | "cacheKey" | "integrityKey" | "deidentified" | "deidentifiedTimestamp" | "markedForExpungepment" | "expungementTimestamp" | "containsSensitiveData" | "sensitivityClassificationTypeEnum" | "version" | "correlationUuid" | "externalId" | "comment" | "recordType" | "projectUuid") | {
    name: "project";
    as?: string;
    fields: FieldsProject;
    args?: {
        $where?: WhereProject;
    };
} | {
    name: "haraList";
    as?: string;
    fields: FieldsHara;
    args?: {
        $where?: WhereHara;
        $orderBy?: OrderByHara;
    };
} | {
    name: "riskReductionMeasureList";
    as?: string;
    fields: FieldsRiskReductionMeasure;
    args?: {
        $where?: WhereRiskReductionMeasure;
        $orderBy?: OrderByRiskReductionMeasure;
    };
})[];
