import type { FieldsCspCapability } from "./FieldsCspCapability";
import type { WhereCspCapability } from "./WhereCspCapability";
import type { OrderByCspCapability } from "./OrderByCspCapability";
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export declare type FieldsCsp = (("id" | "enabled" | "hasKeyFile" | "isHardware" | "compliance" | "init" | "uuid" | "shortDescription" | "longDescription" | "created" | "creator" | "metadata" | "updated" | "updaterIdentityUuid" | "valid" | "archived" | "cacheKey" | "integrityKey" | "deidentified" | "deidentifiedTimestamp" | "markedForExpungepment" | "expungementTimestamp" | "containsSensitiveData" | "sensitivityClassificationTypeEnum" | "version" | "correlationUuid" | "externalId" | "comment" | "recordType") | {
    name: "cspCapabilityList";
    as?: string;
    fields: FieldsCspCapability;
    args?: {
        $where?: WhereCspCapability;
        $orderBy?: OrderByCspCapability;
    };
})[];
