import type { FieldsRisk } from "./FieldsRisk";
import type { WhereRiskType } from "./WhereRiskType";
import type { WhereRisk } from "./WhereRisk";
import type { OrderByRisk } from "./OrderByRisk";
import type { OrderByRiskType } from "./OrderByRiskType";
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export declare type FieldsRiskType = (("id" | "enum" | "name" | "parentId" | "uuid" | "shortDescription" | "longDescription" | "created" | "creator" | "metadata" | "updated" | "updaterIdentityUuid" | "valid" | "archived" | "cacheKey" | "integrityKey" | "deidentified" | "deidentifiedTimestamp" | "markedForExpungepment" | "expungementTimestamp" | "containsSensitiveData" | "sensitivityClassificationTypeEnum" | "version" | "correlationUuid" | "externalId" | "comment" | "recordType" | "parentUuid") | {
    name: "riskType";
    as?: string;
    fields: FieldsRiskType;
    args?: {
        $where?: WhereRiskType;
    };
} | {
    name: "riskList";
    as?: string;
    fields: FieldsRisk;
    args?: {
        $where?: WhereRisk;
        $orderBy?: OrderByRisk;
    };
} | {
    name: "riskTypeList";
    as?: string;
    fields: FieldsRiskType;
    args?: {
        $where?: WhereRiskType;
        $orderBy?: OrderByRiskType;
    };
})[];
