import type { FieldsHazop } from "./FieldsHazop";
import type { FieldsOdd } from "./FieldsOdd";
import type { FieldsProject } from "./FieldsProject";
import type { FieldsHara } from "./FieldsHara";
import type { WhereHazop } from "./WhereHazop";
import type { WhereOdd } from "./WhereOdd";
import type { WhereProject } from "./WhereProject";
import type { WhereHara } from "./WhereHara";
import type { OrderByHara } from "./OrderByHara";
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export declare type FieldsHazardousEvent = (("id" | "hrId" | "projectId" | "hazopId" | "oddId" | "description" | "remarks" | "uuid" | "shortDescription" | "longDescription" | "created" | "creator" | "metadata" | "updated" | "updaterIdentityUuid" | "valid" | "archived" | "cacheKey" | "integrityKey" | "deidentified" | "deidentifiedTimestamp" | "markedForExpungepment" | "expungementTimestamp" | "containsSensitiveData" | "sensitivityClassificationTypeEnum" | "version" | "correlationUuid" | "externalId" | "comment" | "recordType" | "hazopUuid" | "oddUuid" | "projectUuid") | {
    name: "hazop";
    as?: string;
    fields: FieldsHazop;
    args?: {
        $where?: WhereHazop;
    };
} | {
    name: "odd";
    as?: string;
    fields: FieldsOdd;
    args?: {
        $where?: WhereOdd;
    };
} | {
    name: "project";
    as?: string;
    fields: FieldsProject;
    args?: {
        $where?: WhereProject;
    };
} | {
    name: "haraList";
    as?: string;
    fields: FieldsHara;
    args?: {
        $where?: WhereHara;
        $orderBy?: OrderByHara;
    };
})[];
