import type { FieldsProject } from "./FieldsProject";
import type { FieldsOdd } from "./FieldsOdd";
import type { WhereProject } from "./WhereProject";
import type { WhereOdd } from "./WhereOdd";
import type { OrderByOdd } from "./OrderByOdd";
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export declare type FieldsConsideredSituationalAttribute = (("id" | "hrId" | "projectId" | "type" | "value" | "uuid" | "shortDescription" | "longDescription" | "created" | "creator" | "metadata" | "updated" | "updaterIdentityUuid" | "valid" | "archived" | "cacheKey" | "integrityKey" | "deidentified" | "deidentifiedTimestamp" | "markedForExpungepment" | "expungementTimestamp" | "containsSensitiveData" | "sensitivityClassificationTypeEnum" | "version" | "correlationUuid" | "externalId" | "comment" | "recordType" | "projectUuid") | {
    name: "project";
    as?: string;
    fields: FieldsProject;
    args?: {
        $where?: WhereProject;
    };
} | {
    name: "oddList1";
    as?: string;
    fields: FieldsOdd;
    args?: {
        $where?: WhereOdd;
        $orderBy?: OrderByOdd;
    };
} | {
    name: "oddList2";
    as?: string;
    fields: FieldsOdd;
    args?: {
        $where?: WhereOdd;
        $orderBy?: OrderByOdd;
    };
} | {
    name: "oddList3";
    as?: string;
    fields: FieldsOdd;
    args?: {
        $where?: WhereOdd;
        $orderBy?: OrderByOdd;
    };
} | {
    name: "oddList4";
    as?: string;
    fields: FieldsOdd;
    args?: {
        $where?: WhereOdd;
        $orderBy?: OrderByOdd;
    };
})[];
