import type { FieldsProjectAttributeType } from "./FieldsProjectAttributeType";
import type { FieldsProjectAttributeTypeValue } from "./FieldsProjectAttributeTypeValue";
import type { FieldsProject } from "./FieldsProject";
import type { WhereProjectAttributeType } from "./WhereProjectAttributeType";
import type { WhereProjectAttributeTypeValue } from "./WhereProjectAttributeTypeValue";
import type { WhereProject } from "./WhereProject";
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export declare type FieldsProjectAttribute = (("id" | "projectId" | "projectAttributeTypeId" | "projectAttributeTypeValueId" | "projectAttributeTypeEnum" | "projectAttributeTypeValueEnum" | "name" | "value" | "uuid" | "shortDescription" | "longDescription" | "created" | "creator" | "metadata" | "updated" | "updaterIdentityUuid" | "valid" | "archived" | "cacheKey" | "integrityKey" | "deidentified" | "deidentifiedTimestamp" | "markedForExpungepment" | "expungementTimestamp" | "containsSensitiveData" | "sensitivityClassificationTypeEnum" | "version" | "correlationUuid" | "externalId" | "comment" | "recordType" | "projectAttributeTypeUuid" | "projectAttributeTypeValueUuid" | "projectUuid") | {
    name: "projectAttributeType";
    as?: string;
    fields: FieldsProjectAttributeType;
    args?: {
        $where?: WhereProjectAttributeType;
    };
} | {
    name: "projectAttributeTypeValue";
    as?: string;
    fields: FieldsProjectAttributeTypeValue;
    args?: {
        $where?: WhereProjectAttributeTypeValue;
    };
} | {
    name: "project";
    as?: string;
    fields: FieldsProject;
    args?: {
        $where?: WhereProject;
    };
})[];
