import type { FieldsPki } from "./FieldsPki";
import type { FieldsCertificateAuthorityCertificateToken } from "./FieldsCertificateAuthorityCertificateToken";
import type { FieldsCertificateToken } from "./FieldsCertificateToken";
import type { WherePki } from "./WherePki";
import type { WhereCertificateAuthorityCertificateToken } from "./WhereCertificateAuthorityCertificateToken";
import type { WhereCertificateToken } from "./WhereCertificateToken";
import type { OrderByCertificateAuthorityCertificateToken } from "./OrderByCertificateAuthorityCertificateToken";
import type { OrderByCertificateToken } from "./OrderByCertificateToken";
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export declare type FieldsCertificateAuthority = (("id" | "pkiId" | "name" | "description" | "status" | "isRoot" | "hasValidToken" | "uuid" | "shortDescription" | "longDescription" | "created" | "creator" | "metadata" | "updated" | "updaterIdentityUuid" | "valid" | "archived" | "cacheKey" | "integrityKey" | "deidentified" | "deidentifiedTimestamp" | "markedForExpungepment" | "expungementTimestamp" | "containsSensitiveData" | "sensitivityClassificationTypeEnum" | "version" | "correlationUuid" | "externalId" | "comment" | "recordType" | "pkiUuid") | {
    name: "pki";
    as?: string;
    fields: FieldsPki;
    args?: {
        $where?: WherePki;
    };
} | {
    name: "certificateAuthorityCertificateTokenList";
    as?: string;
    fields: FieldsCertificateAuthorityCertificateToken;
    args?: {
        $where?: WhereCertificateAuthorityCertificateToken;
        $orderBy?: OrderByCertificateAuthorityCertificateToken;
    };
} | {
    name: "certificateTokenList";
    as?: string;
    fields: FieldsCertificateToken;
    args?: {
        $where?: WhereCertificateToken;
        $orderBy?: OrderByCertificateToken;
    };
} | {
    name: "certificateTokenList";
    as?: string;
    fields: FieldsCertificateToken;
    args?: {
        $where?: WhereCertificateToken | [WhereCertificateToken, WhereCertificateAuthorityCertificateToken];
        $orderBy?: OrderByCertificateToken;
    };
})[];
