/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export declare type OrderByHara = {
    id: "asc" | "desc";
} | {
    hrId: "asc" | "desc";
} | {
    userId: "asc" | "desc";
} | {
    projectId: "asc" | "desc";
} | {
    hazardousEventId: "asc" | "desc";
} | {
    hazardId: "asc" | "desc";
} | {
    existingExternalMeasureId: "asc" | "desc";
} | {
    initialSeverityId: "asc" | "desc";
} | {
    initialSeverityJustification: "asc" | "desc";
} | {
    initialExposureId: "asc" | "desc";
} | {
    initialExposureJustification: "asc" | "desc";
} | {
    initialAvoidabilityId: "asc" | "desc";
} | {
    initialAvoidabilityJustification: "asc" | "desc";
} | {
    initialRiskClassId: "asc" | "desc";
} | {
    targetRiskReductionMeasureTypeId: "asc" | "desc";
} | {
    safetyTargetType: "asc" | "desc";
} | {
    allocatedSILId: "asc" | "desc";
} | {
    riskReductionMeasureId: "asc" | "desc";
} | {
    finalSeverityId: "asc" | "desc";
} | {
    finalSeverityJustification: "asc" | "desc";
} | {
    finalExposureId: "asc" | "desc";
} | {
    finalExposureJustification: "asc" | "desc";
} | {
    finalAvoidabilityId: "asc" | "desc";
} | {
    finalAvoidabilityJustification: "asc" | "desc";
} | {
    finalRiskClassId: "asc" | "desc";
} | {
    remarks: "asc" | "desc";
} | {
    uuid: "asc" | "desc";
} | {
    shortDescription: "asc" | "desc";
} | {
    longDescription: "asc" | "desc";
} | {
    created: "asc" | "desc";
} | {
    creator: "asc" | "desc";
} | {
    metadata: "asc" | "desc";
} | {
    updated: "asc" | "desc";
} | {
    updaterIdentityUuid: "asc" | "desc";
} | {
    valid: "asc" | "desc";
} | {
    archived: "asc" | "desc";
} | {
    cacheKey: "asc" | "desc";
} | {
    integrityKey: "asc" | "desc";
} | {
    deidentified: "asc" | "desc";
} | {
    deidentifiedTimestamp: "asc" | "desc";
} | {
    markedForExpungepment: "asc" | "desc";
} | {
    expungementTimestamp: "asc" | "desc";
} | {
    containsSensitiveData: "asc" | "desc";
} | {
    sensitivityClassificationTypeEnum: "asc" | "desc";
} | {
    version: "asc" | "desc";
} | {
    correlationUuid: "asc" | "desc";
} | {
    externalId: "asc" | "desc";
} | {
    comment: "asc" | "desc";
} | {
    recordType: "asc" | "desc";
} | ({
    id: "asc" | "desc";
} | {
    hrId: "asc" | "desc";
} | {
    userId: "asc" | "desc";
} | {
    projectId: "asc" | "desc";
} | {
    hazardousEventId: "asc" | "desc";
} | {
    hazardId: "asc" | "desc";
} | {
    existingExternalMeasureId: "asc" | "desc";
} | {
    initialSeverityId: "asc" | "desc";
} | {
    initialSeverityJustification: "asc" | "desc";
} | {
    initialExposureId: "asc" | "desc";
} | {
    initialExposureJustification: "asc" | "desc";
} | {
    initialAvoidabilityId: "asc" | "desc";
} | {
    initialAvoidabilityJustification: "asc" | "desc";
} | {
    initialRiskClassId: "asc" | "desc";
} | {
    targetRiskReductionMeasureTypeId: "asc" | "desc";
} | {
    safetyTargetType: "asc" | "desc";
} | {
    allocatedSILId: "asc" | "desc";
} | {
    riskReductionMeasureId: "asc" | "desc";
} | {
    finalSeverityId: "asc" | "desc";
} | {
    finalSeverityJustification: "asc" | "desc";
} | {
    finalExposureId: "asc" | "desc";
} | {
    finalExposureJustification: "asc" | "desc";
} | {
    finalAvoidabilityId: "asc" | "desc";
} | {
    finalAvoidabilityJustification: "asc" | "desc";
} | {
    finalRiskClassId: "asc" | "desc";
} | {
    remarks: "asc" | "desc";
} | {
    uuid: "asc" | "desc";
} | {
    shortDescription: "asc" | "desc";
} | {
    longDescription: "asc" | "desc";
} | {
    created: "asc" | "desc";
} | {
    creator: "asc" | "desc";
} | {
    metadata: "asc" | "desc";
} | {
    updated: "asc" | "desc";
} | {
    updaterIdentityUuid: "asc" | "desc";
} | {
    valid: "asc" | "desc";
} | {
    archived: "asc" | "desc";
} | {
    cacheKey: "asc" | "desc";
} | {
    integrityKey: "asc" | "desc";
} | {
    deidentified: "asc" | "desc";
} | {
    deidentifiedTimestamp: "asc" | "desc";
} | {
    markedForExpungepment: "asc" | "desc";
} | {
    expungementTimestamp: "asc" | "desc";
} | {
    containsSensitiveData: "asc" | "desc";
} | {
    sensitivityClassificationTypeEnum: "asc" | "desc";
} | {
    version: "asc" | "desc";
} | {
    correlationUuid: "asc" | "desc";
} | {
    externalId: "asc" | "desc";
} | {
    comment: "asc" | "desc";
} | {
    recordType: "asc" | "desc";
})[];
