/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export declare type OrderByCspCapability = {
    id: "asc" | "desc";
} | {
    cspId: "asc" | "desc";
} | {
    keyDeleteCmdId: "asc" | "desc";
} | {
    keyCreateCmdId: "asc" | "desc";
} | {
    keyImportCmdId: "asc" | "desc";
} | {
    keyExportCmdId: "asc" | "desc";
} | {
    enabled: "asc" | "desc";
} | {
    uuid: "asc" | "desc";
} | {
    shortDescription: "asc" | "desc";
} | {
    longDescription: "asc" | "desc";
} | {
    created: "asc" | "desc";
} | {
    creator: "asc" | "desc";
} | {
    metadata: "asc" | "desc";
} | {
    updated: "asc" | "desc";
} | {
    updaterIdentityUuid: "asc" | "desc";
} | {
    valid: "asc" | "desc";
} | {
    archived: "asc" | "desc";
} | {
    cacheKey: "asc" | "desc";
} | {
    integrityKey: "asc" | "desc";
} | {
    deidentified: "asc" | "desc";
} | {
    deidentifiedTimestamp: "asc" | "desc";
} | {
    markedForExpungepment: "asc" | "desc";
} | {
    expungementTimestamp: "asc" | "desc";
} | {
    containsSensitiveData: "asc" | "desc";
} | {
    sensitivityClassificationTypeEnum: "asc" | "desc";
} | {
    version: "asc" | "desc";
} | {
    correlationUuid: "asc" | "desc";
} | {
    externalId: "asc" | "desc";
} | {
    comment: "asc" | "desc";
} | {
    recordType: "asc" | "desc";
} | ({
    id: "asc" | "desc";
} | {
    cspId: "asc" | "desc";
} | {
    keyDeleteCmdId: "asc" | "desc";
} | {
    keyCreateCmdId: "asc" | "desc";
} | {
    keyImportCmdId: "asc" | "desc";
} | {
    keyExportCmdId: "asc" | "desc";
} | {
    enabled: "asc" | "desc";
} | {
    uuid: "asc" | "desc";
} | {
    shortDescription: "asc" | "desc";
} | {
    longDescription: "asc" | "desc";
} | {
    created: "asc" | "desc";
} | {
    creator: "asc" | "desc";
} | {
    metadata: "asc" | "desc";
} | {
    updated: "asc" | "desc";
} | {
    updaterIdentityUuid: "asc" | "desc";
} | {
    valid: "asc" | "desc";
} | {
    archived: "asc" | "desc";
} | {
    cacheKey: "asc" | "desc";
} | {
    integrityKey: "asc" | "desc";
} | {
    deidentified: "asc" | "desc";
} | {
    deidentifiedTimestamp: "asc" | "desc";
} | {
    markedForExpungepment: "asc" | "desc";
} | {
    expungementTimestamp: "asc" | "desc";
} | {
    containsSensitiveData: "asc" | "desc";
} | {
    sensitivityClassificationTypeEnum: "asc" | "desc";
} | {
    version: "asc" | "desc";
} | {
    correlationUuid: "asc" | "desc";
} | {
    externalId: "asc" | "desc";
} | {
    comment: "asc" | "desc";
} | {
    recordType: "asc" | "desc";
})[];
