/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export declare type OrderByAuthorization = {
    id: "asc" | "desc";
} | {
    uuid: "asc" | "desc";
} | {
    serviceName: "asc" | "desc";
} | {
    key: "asc" | "desc";
} | {
    secret: "asc" | "desc";
} | {
    created: "asc" | "desc";
} | ({
    id: "asc" | "desc";
} | {
    uuid: "asc" | "desc";
} | {
    serviceName: "asc" | "desc";
} | {
    key: "asc" | "desc";
} | {
    secret: "asc" | "desc";
} | {
    created: "asc" | "desc";
})[];
