import type { ReturnBaseRiskCategory } from "./ReturnBaseRiskCategory";
import type { ReturnBaseRiskType } from "./ReturnBaseRiskType";
import type { ReturnBaseRiskAttribute } from "./ReturnBaseRiskAttribute";
import type { ReturnBaseRiskAttributeType } from "./ReturnBaseRiskAttributeType";
import type { ReturnBaseRiskDiscussion } from "./ReturnBaseRiskDiscussion";
import type { ReturnBaseRiskEvaluation } from "./ReturnBaseRiskEvaluation";
import type { ReturnBaseRiskEvaluationEntry } from "./ReturnBaseRiskEvaluationEntry";
import type { ReturnBaseRiskMedia } from "./ReturnBaseRiskMedia";
import type { ReturnBaseMedia } from "./ReturnBaseMedia";
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export interface ReturnBaseRisk {
    id?: number;
    projectId?: number;
    riskTypeId?: number | null;
    riskTypeEnum?: string;
    riskCategoryId?: number;
    riskCategoryEnum?: string;
    name?: string;
    sectionNumber?: string | null;
    referenceUrl?: string | null;
    location?: string | null;
    persons?: string | null;
    activity?: string | null;
    photoUrl?: string | null;
    uuid?: string;
    shortDescription?: string | null;
    longDescription?: string | null;
    created?: string;
    creator?: string;
    metadata?: string | null;
    updated?: string | null;
    updaterIdentityUuid?: string | null;
    valid?: boolean;
    archived?: boolean;
    cacheKey?: string | null;
    integrityKey?: string | null;
    deidentified?: boolean;
    deidentifiedTimestamp?: number | null;
    markedForExpungepment?: boolean;
    expungementTimestamp?: number | null;
    containsSensitiveData?: boolean;
    sensitivityClassificationTypeEnum?: string;
    version?: string;
    correlationUuid?: string | null;
    externalId?: string | null;
    comment?: string | null;
    recordType?: string | null;
    projectUuid?: string;
    riskCategoryUuid?: string;
    riskTypeUuid?: string | null;
    risk?: ReturnBaseRisk;
    riskCategory?: ReturnBaseRiskCategory;
    riskType?: ReturnBaseRiskType;
    riskList?: ReturnBaseRisk[];
    riskAttributeList?: ReturnBaseRiskAttribute[];
    riskAttributeTypeList?: ReturnBaseRiskAttributeType[];
    riskDiscussionList?: ReturnBaseRiskDiscussion[];
    riskEvaluationList?: ReturnBaseRiskEvaluation[];
    riskEvaluationEntryList?: ReturnBaseRiskEvaluationEntry[];
    riskMediaList?: ReturnBaseRiskMedia[];
    mediaList?: ReturnBaseMedia[];
    [k: string]: unknown;
}
