/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export interface ReturnBaseAuthorization {
    id?: number;
    uuid?: string;
    serviceName?: string;
    key?: string;
    secret?: string;
    created?: string;
    [k: string]: unknown;
}
