import type { ReturnBaseRiskCategoryAttributeType } from "./ReturnBaseRiskCategoryAttributeType";
import type { ReturnBaseRiskCategory } from "./ReturnBaseRiskCategory";
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export interface ReturnBaseRiskCategoryAttribute {
    id?: number;
    riskCategoryId?: number;
    riskCategoryAttributeTypeId?: number;
    name?: string | null;
    value?: string | null;
    uuid?: string;
    shortDescription?: string | null;
    longDescription?: string | null;
    created?: string;
    creator?: string;
    metadata?: string | null;
    updated?: string | null;
    updaterIdentityUuid?: string | null;
    valid?: boolean;
    archived?: boolean;
    cacheKey?: string | null;
    integrityKey?: string | null;
    deidentified?: boolean;
    deidentifiedTimestamp?: number | null;
    markedForExpungepment?: boolean;
    expungementTimestamp?: number | null;
    containsSensitiveData?: boolean;
    sensitivityClassificationTypeEnum?: string;
    version?: string;
    correlationUuid?: string | null;
    externalId?: string | null;
    comment?: string | null;
    recordType?: string | null;
    riskCategoryAttributeTypeUuid?: string;
    riskCategoryUuid?: string;
    riskCategoryAttributeType?: ReturnBaseRiskCategoryAttributeType;
    riskCategory?: ReturnBaseRiskCategory;
    [k: string]: unknown;
}
