import type { ReturnBaseRisk } from "./ReturnBaseRisk";
import type { ReturnBaseRiskCategoryAttribute } from "./ReturnBaseRiskCategoryAttribute";
import type { ReturnBaseRiskCategoryAttributeType } from "./ReturnBaseRiskCategoryAttributeType";
import type { ReturnBaseRiskCategoryProject } from "./ReturnBaseRiskCategoryProject";
import type { ReturnBaseProject } from "./ReturnBaseProject";
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export interface ReturnBaseRiskCategory {
    id?: number;
    sectionNumber?: string | null;
    enum?: string;
    name?: string;
    referenceUrl?: string | null;
    uuid?: string;
    shortDescription?: string | null;
    longDescription?: string | null;
    created?: string;
    creator?: string;
    metadata?: string | null;
    updated?: string | null;
    updaterIdentityUuid?: string | null;
    valid?: boolean;
    archived?: boolean;
    cacheKey?: string | null;
    integrityKey?: string | null;
    deidentified?: boolean;
    deidentifiedTimestamp?: number | null;
    markedForExpungepment?: boolean;
    expungementTimestamp?: number | null;
    containsSensitiveData?: boolean;
    sensitivityClassificationTypeEnum?: string;
    version?: string;
    correlationUuid?: string | null;
    externalId?: string | null;
    comment?: string | null;
    recordType?: string | null;
    riskList?: ReturnBaseRisk[];
    riskCategoryAttributeList?: ReturnBaseRiskCategoryAttribute[];
    riskCategoryAttributeTypeList?: ReturnBaseRiskCategoryAttributeType[];
    riskCategoryProjectList?: ReturnBaseRiskCategoryProject[];
    projectList?: ReturnBaseProject[];
    [k: string]: unknown;
}
