import type { ReturnBaseCertificateAuthority } from "./ReturnBaseCertificateAuthority";
import type { ReturnBaseOrganization } from "./ReturnBaseOrganization";
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export interface ReturnBaseCertificateAuthorityOrganization {
    id?: number;
    certificateAuthorityId?: number | null;
    organizationId?: number | null;
    status?: "ENABLED" | "DISABLED" | "SUSPENDED" | null;
    uuid?: string;
    shortDescription?: string | null;
    longDescription?: string | null;
    created?: string;
    creator?: string;
    metadata?: string | null;
    updated?: string | null;
    updaterIdentityUuid?: string | null;
    valid?: boolean;
    archived?: boolean;
    cacheKey?: string | null;
    integrityKey?: string | null;
    deidentified?: boolean;
    deidentifiedTimestamp?: number | null;
    markedForExpungepment?: boolean;
    expungementTimestamp?: number | null;
    containsSensitiveData?: boolean;
    sensitivityClassificationTypeEnum?: string;
    version?: string;
    correlationUuid?: string | null;
    externalId?: string | null;
    comment?: string | null;
    recordType?: string | null;
    certificateAuthorityUuid?: string | null;
    organizationUuid?: string | null;
    certificateAuthority?: ReturnBaseCertificateAuthority;
    organization?: ReturnBaseOrganization;
    [k: string]: unknown;
}
