import type { ReturnBaseRiskCategory } from "./ReturnBaseRiskCategory";
import type { ReturnBaseRiskCategoryAttribute } from "./ReturnBaseRiskCategoryAttribute";
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export interface ReturnBaseRiskCategoryAttributeType {
    id?: number;
    riskCategoryId?: number | null;
    parentId?: number | null;
    enum?: string;
    name?: string;
    labelNumber?: string | null;
    defaultValue?: string;
    isRequired?: boolean;
    jsonSchema?: string;
    label?: string | null;
    placeholderText?: string | null;
    helpMarkdownText?: string | null;
    isMedia?: boolean | null;
    uuid?: string;
    shortDescription?: string | null;
    longDescription?: string | null;
    created?: string;
    creator?: string;
    metadata?: string | null;
    updated?: string | null;
    updaterIdentityUuid?: string | null;
    valid?: boolean;
    archived?: boolean;
    cacheKey?: string | null;
    integrityKey?: string | null;
    deidentified?: boolean;
    deidentifiedTimestamp?: number | null;
    markedForExpungepment?: boolean;
    expungementTimestamp?: number | null;
    containsSensitiveData?: boolean;
    sensitivityClassificationTypeEnum?: string;
    version?: string;
    correlationUuid?: string | null;
    externalId?: string | null;
    comment?: string | null;
    recordType?: string | null;
    parentUuid?: string | null;
    riskCategoryUuid?: string | null;
    riskCategoryAttributeType?: ReturnBaseRiskCategoryAttributeType;
    riskCategory?: ReturnBaseRiskCategory;
    riskCategoryAttributeList?: ReturnBaseRiskCategoryAttribute[];
    riskCategoryAttributeTypeList?: ReturnBaseRiskCategoryAttributeType[];
    [k: string]: unknown;
}
