import type { ReturnBaseProject } from "./ReturnBaseProject";
import type { ReturnBaseSil } from "./ReturnBaseSil";
import type { ReturnBaseRiskReductionMeasureType } from "./ReturnBaseRiskReductionMeasureType";
import type { ReturnBaseHara } from "./ReturnBaseHara";
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export interface ReturnBaseRiskReductionMeasure {
    id?: number;
    hrId?: string;
    projectId?: number | null;
    typeId?: number | null;
    targetSILId?: number | null;
    description?: string | null;
    remarks?: string | null;
    uuid?: string;
    shortDescription?: string | null;
    longDescription?: string | null;
    created?: string;
    creator?: string;
    metadata?: string | null;
    updated?: string | null;
    updaterIdentityUuid?: string | null;
    valid?: boolean;
    archived?: boolean;
    cacheKey?: string | null;
    integrityKey?: string | null;
    deidentified?: boolean;
    deidentifiedTimestamp?: number | null;
    markedForExpungepment?: boolean;
    expungementTimestamp?: number | null;
    containsSensitiveData?: boolean;
    sensitivityClassificationTypeEnum?: string;
    version?: string;
    correlationUuid?: string | null;
    externalId?: string | null;
    comment?: string | null;
    recordType?: string | null;
    projectUuid?: string | null;
    targetSILUuid?: string | null;
    typeUuid?: string | null;
    project?: ReturnBaseProject;
    sil?: ReturnBaseSil;
    riskReductionMeasureType?: ReturnBaseRiskReductionMeasureType;
    haraList?: ReturnBaseHara[];
    [k: string]: unknown;
}
