import type { ReturnBaseOrganization } from "./ReturnBaseOrganization";
import type { ReturnBaseUserOrganizationRole } from "./ReturnBaseUserOrganizationRole";
import type { ReturnBaseUserProject } from "./ReturnBaseUserProject";
import type { ReturnBaseUser } from "./ReturnBaseUser";
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export interface ReturnBaseOrganizationRole {
    id?: number;
    organizationId?: number;
    organizationEnum?: string;
    enum?: string;
    name?: string;
    uuid?: string;
    shortDescription?: string | null;
    longDescription?: string | null;
    created?: string;
    creator?: string;
    metadata?: string | null;
    updated?: string | null;
    updaterIdentityUuid?: string | null;
    valid?: boolean;
    archived?: boolean;
    cacheKey?: string | null;
    integrityKey?: string | null;
    deidentified?: boolean;
    deidentifiedTimestamp?: number | null;
    markedForExpungepment?: boolean;
    expungementTimestamp?: number | null;
    containsSensitiveData?: boolean;
    sensitivityClassificationTypeEnum?: string;
    version?: string;
    correlationUuid?: string | null;
    externalId?: string | null;
    comment?: string | null;
    recordType?: string | null;
    organizationUuid?: string;
    organization?: ReturnBaseOrganization;
    userOrganizationRoleList?: ReturnBaseUserOrganizationRole[];
    userProjectList?: ReturnBaseUserProject[];
    userList?: ReturnBaseUser[];
    [k: string]: unknown;
}
