import type { ReturnBaseFunctionTask } from "./ReturnBaseFunctionTask";
import type { ReturnBaseGuideword } from "./ReturnBaseGuideword";
import type { ReturnBaseProject } from "./ReturnBaseProject";
import type { ReturnBaseHazardousEvent } from "./ReturnBaseHazardousEvent";
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export interface ReturnBaseHazop {
    id?: number;
    hrId?: string;
    projectId?: number | null;
    functionTaskId?: number | null;
    guidewordId?: number | null;
    resultingMalfunction?: string | null;
    remarks?: string | null;
    uuid?: string;
    shortDescription?: string | null;
    longDescription?: string | null;
    created?: string;
    creator?: string;
    metadata?: string | null;
    updated?: string | null;
    updaterIdentityUuid?: string | null;
    valid?: boolean;
    archived?: boolean;
    cacheKey?: string | null;
    integrityKey?: string | null;
    deidentified?: boolean;
    deidentifiedTimestamp?: number | null;
    markedForExpungepment?: boolean;
    expungementTimestamp?: number | null;
    containsSensitiveData?: boolean;
    sensitivityClassificationTypeEnum?: string;
    version?: string;
    correlationUuid?: string | null;
    externalId?: string | null;
    comment?: string | null;
    recordType?: string | null;
    functionTaskUuid?: string | null;
    guidewordUuid?: string | null;
    projectUuid?: string | null;
    functionTask?: ReturnBaseFunctionTask;
    guideword?: ReturnBaseGuideword;
    project?: ReturnBaseProject;
    hazardousEventList?: ReturnBaseHazardousEvent[];
    [k: string]: unknown;
}
